# Generated by Django 4.2.2 on 2023-06-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('trabajador', 'Permisos exclusivo de los trabajadores'), ('cliente', 'Permisos exclusivo de los clientes')),
            },
        ),
    ]
